// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// CreatePasteRequest defines model for CreatePasteRequest.
type CreatePasteRequest struct {
	Expiry      int     `json:"expiry"`
	Files       *[]File `json:"files,omitempty"`
	Pass        *string `json:"pass,omitempty"`
	PassProtect bool    `json:"passProtect"`
	PasteText   string  `json:"pasteText"`
}

// File defines model for File.
type File struct {
	Name string `json:"name"`
	Size int64  `json:"size"`
	Url  string `json:"url"`
}

// Paste defines model for Paste.
type Paste struct {
	Files       *[]File `json:"files"`
	Id          *string `json:"id,omitempty"`
	Protected   *bool   `json:"protected,omitempty"`
	Text        *string `json:"text"`
	TimeoutUnix *int64  `json:"timeoutUnix,omitempty"`
}

// GetPasteParams defines parameters for GetPaste.
type GetPasteParams struct {
	// XPastePassword Password for protected pastes
	XPastePassword *string `json:"X-Paste-Password,omitempty"`
}

// CreatePasteJSONRequestBody defines body for CreatePaste for application/json ContentType.
type CreatePasteJSONRequestBody = CreatePasteRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a new paste
	// (POST /pastes)
	CreatePaste(c *gin.Context)
	// Get a paste
	// (GET /pastes/{id})
	GetPaste(c *gin.Context, id string, params GetPasteParams)
	// Get last created paste ID from session
	// (GET /session/last-paste)
	GetLastPasteSession(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// CreatePaste operation middleware
func (siw *ServerInterfaceWrapper) CreatePaste(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreatePaste(c)
}

// GetPaste operation middleware
func (siw *ServerInterfaceWrapper) GetPaste(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPasteParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Paste-Password" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Paste-Password")]; found {
		var XPastePassword string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Paste-Password, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-Paste-Password", runtime.ParamLocationHeader, valueList[0], &XPastePassword)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Paste-Password: %w", err), http.StatusBadRequest)
			return
		}

		params.XPastePassword = &XPastePassword

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPaste(c, id, params)
}

// GetLastPasteSession operation middleware
func (siw *ServerInterfaceWrapper) GetLastPasteSession(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLastPasteSession(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/pastes", wrapper.CreatePaste)
	router.GET(options.BaseURL+"/pastes/:id", wrapper.GetPaste)
	router.GET(options.BaseURL+"/session/last-paste", wrapper.GetLastPasteSession)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xVS2/cNhD+K8S0hwRQVkriBoVufQaL9mDYKVAg8IEWRzZTimSGw41dQ/+9ICntS2pT",
	"tEUvCy45j2/m+2b0BJ0bvLNoOUD7BKG7x0Hm43eEkvFSBsYr/BgxcLr15DwSa8w2+OA1PabTIB/0EAdo",
	"3zQXXzdNBYO280UF/OgRWtCW8Q4Jxgp6bUoIzTjkw5eEPbTwRX1AVE9w6h+1weQ1xZFE8jH99zJk3+k+",
	"MGl7Nz9ckmPs+Oj91jmD0k4GjO/wgVfcxwoIP0ZNqKB9Pxd5GvQ4ws0emLv9kB7HCjLiRb+sHHAVb9C/",
	"54fe0SC5tOrNBax1LpL5POacaApbXNZAZnKXKP8ZNzYaI29T1UwRl1xptc5UaSiqdZ54ouhPoh/isB7Q",
	"Rf7F6oe/1chx0Y90pW3vkrvC0JH2rJ2FFq6xi4QiM36rrfjmciueXf1w/a6P5nmKrTkhg5+MDkxyY2My",
	"gQp2SKGEeLVpNk3C6Txa6TW08HrTbF5nIfF97nKdE+Sjd2XcEi0yodgqaI9HEgrfGPhbp/IEds4y2uwl",
	"vTe6y371h5Dyz5P9OTJXhn481VZqf74I3tlQ0L5qXv5nCEp1OekpCflBdBmgEiF2HYbQR2Oyui6aZsnb",
	"1u6k0Upo62MW/FdrVtdIOySBRK7oIsRhkGmtTQ0XUlj8VOjPBhNR9ZNWY4p3h7wMe4VMGnfJO5tvxLYX",
	"e7VX6bjTKqsqfHKUUIpfX+Qq02+5u0epkLKrdQfTyVeJ3tEhZslTCUKOZIMYkKWSLIWz5nED1Zma3iLP",
	"UvKS5ICMFKB9/7Ta+O33kMYD2qxXqKZdlsb6XB7VEdWLNbUSvdS0UkqYU5Y2HJKe9wn+KuXNQq3N/6bW",
	"kkM8c3RgQx/JQEirhHHdb6ieFxm/XJNx54iw470AiunF0rSktY5F76JVZ3J+izyrseg4YEj7qTYy8As/",
	"fw0mOS/U8rMMRTHXxQ3+ZWNPvzqr34f1LX1ac4K13wt+FuuycrNmJ3pyg5j6UKKHvA/KJOSPLdRpYY83",
	"4x8BAAD///u415cuCQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
