// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// CreatePasteRequest defines model for CreatePasteRequest.
type CreatePasteRequest struct {
	Expiry      int     `json:"expiry"`
	Pass        *string `json:"pass,omitempty"`
	PassProtect bool    `json:"passProtect"`
	PasteText   string  `json:"pasteText"`
}

// Paste defines model for Paste.
type Paste struct {
	Id          *string `json:"id,omitempty"`
	Protected   *bool   `json:"protected,omitempty"`
	Text        *string `json:"text"`
	TimeoutUnix *int64  `json:"timeoutUnix,omitempty"`
}

// GetPasteParams defines parameters for GetPaste.
type GetPasteParams struct {
	// XPastePassword Password for protected pastes
	XPastePassword *string `json:"X-Paste-Password,omitempty"`
}

// CreatePasteJSONRequestBody defines body for CreatePaste for application/json ContentType.
type CreatePasteJSONRequestBody = CreatePasteRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a new paste
	// (POST /pastes)
	CreatePaste(c *gin.Context)
	// Get a paste
	// (GET /pastes/{id})
	GetPaste(c *gin.Context, id string, params GetPasteParams)
	// Get last created paste ID from session
	// (GET /session/last-paste)
	GetLastPasteSession(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// CreatePaste operation middleware
func (siw *ServerInterfaceWrapper) CreatePaste(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreatePaste(c)
}

// GetPaste operation middleware
func (siw *ServerInterfaceWrapper) GetPaste(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPasteParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Paste-Password" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Paste-Password")]; found {
		var XPastePassword string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Paste-Password, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-Paste-Password", runtime.ParamLocationHeader, valueList[0], &XPastePassword)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Paste-Password: %w", err), http.StatusBadRequest)
			return
		}

		params.XPastePassword = &XPastePassword

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPaste(c, id, params)
}

// GetLastPasteSession operation middleware
func (siw *ServerInterfaceWrapper) GetLastPasteSession(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLastPasteSession(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/pastes", wrapper.CreatePaste)
	router.GET(options.BaseURL+"/pastes/:id", wrapper.GetPaste)
	router.GET(options.BaseURL+"/session/last-paste", wrapper.GetLastPasteSession)
}
